site_name: Robotique (1SX - Cégep de Shawinigan)
site_url: https://nbourre.github.io/1sx_cours_notes/
theme:
  name: material
  language: fr
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate

plugins:
  - search
  - mkdocs-video
  - print-site

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
      toc_depth: 3
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      base_path: .
  - pymdownx.details
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Accueil: index.md
  - Cours 01 - Présentation et rappels:
    - Présentation du cours: 1SX_cours_01_intro_rappels/index.md
    - Rappels sur l'Arduino:
      - Sommaire: 1SX_cours_01b_rappels_no_delay/index.md
      - A - Délai sans blocage: 1SX_cours_01b_rappels_no_delay/01_delai_sans_delay.md
      - B - La communication série: 1SX_cours_01b_rappels_no_delay/02_comm_serie.md
      - C - Lecture d'un bouton: 1SX_cours_01b_rappels_no_delay/03_lecture_du_bouton.md
      - D - PWM et lecture analogique: 1SX_cours_01b_rappels_no_delay/04_pwm_analogique.md
  - Cours 02 - Les capteurs:
    - Les capteurs: 1SX_cours_02_ultrason_hum_temp/index.md
    - Les appareils i2c: 1SX_cours_02b_i2c_gyro/index.md
  - Cours 06:
    - Initiation au mBot Ranger: 1SX_cours_06_intro_ranger/index.md
  - Cours 07:
    - Les moteurs: 1SX_cours_07_dels_moteurs/index.md
  - Cours 08:
    - Les moteurs avec encodeur: 1SX_cours_08_gyro_encodeurs/index.md
  - Cours 09:
    - PID: 1SX_cours_09_PID/index.md
  - Cours 10:
    - Communication série via Bluetooth: 1SX_cours_10_comm_bt/index.md
  - Cours 11:
    - Le capteur de ligne: 1SX_cours_11_line_tracker/index.md
  - Cours 12:
    - Le capteur de distance: 1SX_cours_10_autres_capteurs/index.md
  - ArduinoJson: 1SX_cours_12_ArduinoJson/index.md
  - Extras:
    - Prototypes de fonctions: extra/prototype_fonction/index.md
    - Spécifications du robot Ranger: extra/ranger_specs.md
    - Liste de ressources: ressources/index.md
  - Évaluations:
    - Questions types: questions/index.md