name: Build PDFs (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    container:
      image: pandoc/latex:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create pdf directory
        run: mkdir -p pdf

      - name: Convert Markdown files to PDF (Docker version)
        run: |
          find . -type d -name "1SX_cours_*" | while read dir; do
            count=$(find "$dir" -maxdepth 1 -iname "*.md" | wc -l)
            dirname=$(basename "$dir")

            find "$dir" -maxdepth 1 -iname "*.md" | while read file; do
              filename=$(basename "$file")
              basename_no_ext="${filename%.md}"

              if [ "$count" -eq 1 ]; then
                output="pdf/${dirname}.pdf"
              elif [ "$basename_no_ext" = "readme" ] || [ "$basename_no_ext" = "README" ]; then
                output="pdf/${dirname}__readme.pdf"
              else
                suffix=$(echo "$basename_no_ext" | tr ' ' '_')
                output="pdf/${dirname}_${suffix}.pdf"
              fi

              echo "Converting $file → $output"

              resource_dir=$(dirname "$file")

              pandoc "$file" -o "$output" \
                --from=gfm \
                --pdf-engine=xelatex \
                --lua-filter=.github/filters/ignore.lua \
                --toc --toc-depth=2 -V listings \
                --resource-path=".:$resource_dir"

            done
          done

      - name: Show generated PDFs
        run: ls -lh pdf || true
        
      - name: Upload PDFs (GitHub artifact)
        uses: actions/upload-artifact@v4
        with:
          name: notes-pdf
          path: pdf/**/*.pdf

  package-release:
    runs-on: ubuntu-latest
    needs: build-pdf

    steps:
      - name: Download PDFs artifact
        uses: actions/download-artifact@v4
        with:
          name: notes-pdf
          path: pdf

      - name: Show downloaded PDFs
        run: ls -lhR pdf

      # Ici on est HORS Docker, donc 'zip' est dispo (et au pire, on pourrait l’installer)
      - name: Create zip of all PDFs
        run: |
          zip -r toutes_les_notes.zip pdf

      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: "Notes de cours PDF"
          tag_name: "latest"
          files: |
            pdf/*.pdf
            toutes_les_notes.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
