name: Build PDFs (Docker)

on:
  push:
    branches: [ main ]

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    container:
      image: pandoc/latex:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create pdf directory
        run: mkdir -p pdf

      - name: Convert Markdown files to PDF (Docker version)
        run: |
          find . -type d -name "1SX_cours_*" | while read dir; do
            count=$(find "$dir" -maxdepth 1 -iname "*.md" | wc -l)
            dirname=$(basename "$dir")

            find "$dir" -maxdepth 1 -iname "*.md" | while read file; do
              filename=$(basename "$file")
              basename_no_ext="${filename%.md}"

              if [ "$count" -eq 1 ]; then
                output="pdf/${dirname}.pdf"
              elif [ "$basename_no_ext" = "readme" ] || [ "$basename_no_ext" = "README" ]; then
                output="pdf/${dirname}__readme.pdf"
              else
                suffix=$(echo "$basename_no_ext" | tr ' ' '_')
                output="pdf/${dirname}_${suffix}.pdf"
              fi

              echo "Converting $file → $output"
              pandoc "$file" -o "$output" --from=gfm --pdf-engine=xelatex --lua-filter=.github/filters/ignore.lua --toc --toc-depth=2 -V listings
            done
          done

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: notes-pdf
          path: pdf/
